enum ability_used {
    ABILITY_USED_JUMP = 0x0,
    ABILITY_USED_FLAP = 0x1,
    ABILITY_USED_FLIP = 0x2,
    ABILITY_USED_SWIM = 0x3,
    ABILITY_USED_CLIMB = 0x4,
    ABILITY_USED_BEAK_BARGE = 0x5,
    ABILITY_USED_SLIDE = 0x6,
    ABILITY_USED_EGG = 0x7,
    ABILITY_USED_FLY = 0x8,
    ABILITY_USED_SHOCK = 0x9,
    ABILITY_USED_PECK = 0xA,
    ABILITY_USED_CLAW = 0xB,
    ABILITY_USED_TWIRL = 0xC
};
