typedef enum {
    GAME_SELECT_INITIALIZE = 1,
    GAME_SELECT_IDLE = 2,
    GAME_SELECT_STARTING = 3,
    GAME_SELECT_STARTING_SILLY = 4,
    GAME_SELECT_ERASE_CONFIRMATION = 5,
    GAME_SELECT_DONE = 6
} GameSelectState;
