typedef enum {
    JIGSAW_PICTURE_LEAVE_PODIUM = 1,
    JIGSAW_PICTURE_ENTER_PODIUM = 2,
    JIGSAW_PICTURE_INSTRUCTIONS = 3,
    JIGSAW_PICTURE_WAITING = 4,
    JIGSAW_PICTURE_ADD_PIECE = 5,
    JIGSAW_PICTURE_ADD_ALL = 6,
    JIGSAW_PICTURE_COMPLETE = 7,
    JIGSAW_PICTURE_REMOVE_PIECE = 8
} JigsawPictureState;
